bauteileDB/bauteileDB/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView
from usermanagement import views as register_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('core/', include('core.urls')),
    path('components/', include('components.urls')),
    path('projects/', include('projects.urls')),
    path('rooms/', include('rooms.urls')),
    path('vendors/', include('vendors.urls')),
    path('import/', include('importexport.urls')),
    path('log/', include('log.urls')),
    path('tools/', include('tools.urls')),
    
    path('', include('django.contrib.auth.urls')),  # Auth URLs
    path('logout/', include('usermanagement.urls'), name='logout'),

    path('', RedirectView.as_view(url='/components/articles/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bauteileDB/components/urls.py
from django.urls import path
from .views.component_views import *


app_name = 'components'

urlpatterns = [
    #---------------Article views
    path('articles/', ArticleListView.as_view(), name='article_list'),  # List view for all articles
    path('add-articles/', ArticleAddView.as_view(), name='article-add'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),  # Edit URL
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('articles/<int:pk>/stock/', ArticleStockView.as_view(), name='article_stock'),
    
    #---------------Item views
    path('items/', AllItemsView.as_view(), name='all_items_list'),
    path('articles/<int:article_id>/add-items/', ItemAddView.as_view(), name='item_add'),
    path('items/<int:pk>/edit/', ItemUpdateView.as_view(), name='item_update'),
    path('items/<int:pk>/delete/', ItemDeleteView.as_view(), name='item_delete'),
    path('items/<int:pk>/split/', ItemSplitView.as_view(), name='item_split'),
    path('items/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('bulk_transfer/', BulkTransferView.as_view(), name='bulk_transfer'),
    #---------------Item-Order views
    path('items/<int:item_pk>/order/<int:order_pk>/delete/', 
         OrderDeleteView.as_view(), name='order_delete'),
    path('items/<int:item_pk>/order/<int:order_pk>/finish/', 
         OrderFinishView.as_view(), name='order_finish'),
    path('items/<int:pk>/order', ItemOrderView.as_view(), name='item_order'),
    path('items/<int:pk>/download_qr/', ItemQRDownloadView.as_view(), name='item_qr_download'),
    
    
    #---------------Export
    path('articles/<int:article_id>/export/', ArticleItemsExportView.as_view(), name='article_items_export'),
    path('item/export/', ItemExportView.as_view(), name='item_export'),
    path('articles/export/', ArticleExportView.as_view(), name='article_export'),
]

bauteileDB/log/urls.py
from django.urls import path
from .views import LogListView

app_name = 'log'

urlpatterns = [
    path('', LogListView.as_view(), name='log_list'),
]

bauteileDB/components/models.py
from django.db import models

# Create your models here.

bauteileDB/components/views/component_views.py
import csv
import qrcode
import io
from decimal import Decimal
from urllib.parse import unquote, urlencode
from django import apps
from django.contrib import messages
from django.forms import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from core.views.generic_views import GenericAddView, GenericUpdateView, GenericDeleteView, GenericTableView, GenericExportView
from django.views import View
from core.models.component_models import Article, Item, Unit, Document, Order
from ..filters import AllItemsFilter, ArticleFilter, ItemFilter, ItemStockFilter
from ..tables import AllItemsTable, ArticleTable, ItemTable  # Import all necessary tables
from ..forms import ArticleForm, ItemFormHiddenArticle, ItemCreationForm, BulkTransferForm, ItemSplitForm, OrderForm
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.db import transaction, models
from urllib.parse import urlparse, parse_qs, urlencode
from django.db import IntegrityError
from urllib.parse import urlencode, quote, urlparse, parse_qs, urlunparse
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.base import ContentFile
from log.utils import log_to_database
from django.views.generic import DetailView
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings



# Article views
class ArticleItemsExportView(View):
    def get(self, request, article_id, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="items_of_article_{article_id}.csv"'

        writer = csv.writer(response)
        writer.writerow(['Name', 'Serial Number', 'Quantity', 'Location', 'Assembly'])

        items = Item.objects.filter(article_id=article_id)
        for item in items:
            writer.writerow([item.name, item.serial_number, item.quantity, item.location, item.assembly])

        return response


class ArticleListView(GenericTableView):
    model = Article
    table_class = ArticleTable
    filterset_class = ArticleFilter
    ordering = ['name']


    def get_queryset(self):
        queryset = Article.objects.annotate(
            total_stock=Coalesce(Sum('item__quantity'), 0.0)
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            bulk_actions_modal=[
                {
                    'name': 'Delete Selected',
                    'modal_template': 'modals/bulk_delete_modal.html',
                    'modal_js': 'js/bulk_delete.js',
                    'class': 'btn btn-danger',
                    'modal_target': '#bulkDeleteModal',
                    'bulk_delete_url': reverse_lazy('core:bulk_delete', kwargs={
                        'model_name': 'article',
                        'app_name': 'core' 
                    })
                },
            ],
            **kwargs
        )
        # Add 'Add Article' button information
        context['add_button_url'] = reverse_lazy('components:article-add')
        context['add_button_label'] = 'Add Article'
        
        context['export_button_url'] = reverse_lazy('components:article_export')
        context['export_button_label'] = 'Export'
        
        return context


class ArticleAddView(GenericAddView):
    model = Article
    form_class = ArticleForm
    page_title = "Add New Article"
    success_url_name = 'components:article_list'
    cancel_url_name = 'components:article_list'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method == 'GET':
            default_measurement, created = Unit.objects.get_or_create(
                unit_of_measurement="pcs",
                defaults={'description': 'Standard unit of measurement'}
            )
            kwargs['initial'] = {'unit': default_measurement}
        return kwargs
 
    def form_valid(self, form):

        form.instance.modified_by = self.request.user.username 

        response = super().form_valid(form)
        action = self.request.POST.get('action')

        if action == 'save_and_exit':
            return redirect(self.get_success_url())
        elif action == 'save_and_create_another':
            return redirect(self.request.get_full_path())

        return response


class ArticleUpdateView(GenericUpdateView):
    model = Article
    form_class = ArticleForm
    page_title = "Edit Article"
    success_url_name = 'components:article_list'
    cancel_url_name = 'components:article_list'
    template_name = 'components/article_edit.html'

    def get_form_kwargs(self):
        # Get the default form kwargs
        kwargs = super().get_form_kwargs()

        # Get the current article instance
        article = self.get_object()

        # If this is an update (i.e., the article instance exists)
        if article.pk:
            # Set initial value for suppliers field as a comma-separated string of supplier names
            supplier_names = ', '.join(article.suppliers.values_list('name', flat=True))
            kwargs['initial'] = kwargs.get('initial', {})
            kwargs['initial']['suppliers'] = supplier_names

        if article.manufacturer:
            kwargs['initial']['manufacturer_input'] = article.manufacturer.name

        return kwargs

    def form_valid(self, form):
        form.instance.modified_by = self.request.user.username 
        
        # Save with logging but only once
        self.save_with_logging(form)
        article_instance = form.instance

        # Handle deletion of documents
        for document in article_instance.documents.all():
            if self.request.POST.get(f'delete_document_{document.pk}'):
                document.delete()

        # Handle user actions: 'save_and_exit' or 'save_and_create_another'
        action = self.request.POST.get('action')
        if action == 'save_and_exit':
            return redirect(self.get_success_url())
        elif action == 'save_and_create_another':
            return redirect(self.request.get_full_path())

        return super().form_valid(form)


class ArticleDeleteView(GenericDeleteView):
    model = Article
    page_title = "Delete Article"
    success_url_name = 'components:article_list'
    cancel_url_name = 'components:article_list'


class ArticleExportView(GenericExportView):
    model = Article
    filterset_class = ArticleFilter
    table_class = ArticleTable


class ArticleItemsExportView(GenericExportView):
    model = Item
    filterset_class = ItemStockFilter
    table_class = AllItemsTable

    def get_filtered_queryset(self):
        queryset = self.model.objects.all()
        if self.filterset_class:
            filterset = self.filterset_class(self.request.GET, queryset=queryset)
            queryset = filterset.qs

        # Filter by article_id
        article_id = self.kwargs.get('article_id')
        if article_id:
            queryset = queryset.filter(article_id=article_id)

        return queryset


# Item views


class ItemListView(GenericTableView):
    model = Item
    table_class = ItemTable
    filterset_class = ItemFilter
    ordering = ['article__name']  # Default ordering by article name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            bulk_actions_modal=[
                {
                    'name': 'Delete Selected',
                    'modal_template': 'modals/bulk_delete_modal.html',
                    'modal_js': 'js/bulk_delete.js',
                    'class': 'btn btn-danger',
                    'modal_target': '#bulkDeleteModal',
                    'bulk_delete_url': reverse_lazy('core:bulk_delete', kwargs={
                        'model_name': 'item',
                        'app_name': 'core' 
                    })
                },
            ],
            bulk_actions=[
                {
                    'name': 'Transfer Selected',
                    'class': 'btn btn-primary',
                    'bulk_action_url': reverse_lazy('components:bulk_transfer'),
                    'method': 'GET',
                }
                ],
            **kwargs
        )
        
        # Export Button
        context['export_button_url'] = reverse_lazy('components:item_export')
        context['export_button_label'] = 'Export'
        
        return context


class ItemAddView(LoginRequiredMixin,View):
    form_class = ItemCreationForm
    template_name = 'components/add_item_form.html'
    page_title = "Add New Item"
    login_url = '/login'

    def dispatch(self, request, *args, **kwargs):
        article_id = self.kwargs.get('article_id') or self.kwargs.get('pk')
        self.article = get_object_or_404(Article, pk=article_id)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(article=self.article)
        context = {
            'form': form,
            'page_title': self.page_title,
            'cancel_url': self.get_cancel_url(),
        }
        return render(request, self.template_name, context)

    def log_addition_serial_numbers(self, obj, quant, serial_nums):
        # Get the name of the newly added object
        object_name = str(obj)
        # Log the addition of the object
        log_message = f"{quant} new {object_name} added: {serial_nums} by {self.request.user} from IP {self.request.META.get('REMOTE_ADDR')}"
        # Log the information to the database
        log_to_database('INFO', log_message, user=self.request.user)
    
    def log_addition_no_serial_numbers(self, obj, quant):
        # Get the name of the newly added object
        object_name = str(obj)

bauteileDB/components/templates/components/add_item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'styles/forms.css' %}">
<h2 class="text-center">{{ custom_title|default:page_title }}</h2>

<div class="d-flex justify-content-center">
    <div class="card bordered-form w-100" style="max-width: 600px;">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                
                <!-- Informative message about location and sublocation -->
                <div id="location-info" class="alert alert-warning d-none mt-3">
                    The location and sublocation are automatically determined by the selected assembly and cannot be edited.
                </div>
                
                <!-- Buttons -->
                <div class="text-center mt-4">
                    <button type="submit" name="action" value="save_and_exit" class="btn btn-primary me-2">
                        <i class="bi bi-save me-1"></i> Save
                    </button>
                    <button type="submit" name="action" value="save_and_create_another" class="btn btn-secondary me-2">
                        <i class="bi bi-plus-circle me-1"></i> Save and Create Another
                    </button>
                    <a href="{{ cancel_url }}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-circle me-1"></i> Cancel
                    </a>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/transfer_items.js' %}" defer></script>
<script>
    // Initialize Bootstrap tooltips (if any)
    document.addEventListener('DOMContentLoaded', function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        tooltipTriggerList.forEach(function (tooltipTriggerEl) {
            new bootstrap.Tooltip(tooltipTriggerEl);
        });

        // Handle location info visibility based on assembly selection
        const assemblyInput = document.getElementById('id_assembly_input'); // Adjust ID if necessary
        const locationInfo = document.getElementById('location-info');

        if (assemblyInput) {
            assemblyInput.addEventListener('change', function () {
                if (assemblyInput.value) {
                    locationInfo.classList.remove('d-none');
                } else {
                    locationInfo.classList.add('d-none');
                }
            });
        }
    });
</script>
{% endblock %}

bauteileDB/components/templates/components/article_actions_column.html
<a href="{% url 'components:article_stock' record.pk %}?back_url={{ request.get_full_path|urlencode }}" class="btn btn-sm btn-info">
    <i class="bi bi-eye"></i> View Stock
</a>
<a href="{% url 'components:article_update' record.pk %}?back_url={{ request.get_full_path|urlencode }}" class="btn btn-sm btn-primary">
    <i class="bi bi-pencil-square"></i> Edit
</a>

bauteileDB/components/templates/components/article_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'styles/forms.css' %}">

<h2 class="text-center mb-4">{{ custom_title|default:page_title }}</h2>

<div class="d-flex justify-content-center">
    <div class="card bordered-form w-100" style="max-width: 600px;">
        <div class="card-body">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Display existing documents -->
                {% if object.documents.all %}
                    <h4 class="mb-3">Existing Documents</h4>
                    <ul class="list-group mb-4">
                        {% for document in object.documents.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div>
                                    <i class="bi bi-file-earmark-text"></i>
                                    <a href="{{ document.file.url }}" target="_blank">{{ document.file.name }}</a>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="delete_document_{{ document.pk }}" id="delete_document_{{ document.pk }}">
                                    <label class="form-check-label" for="delete_document_{{ document.pk }}">
                                        Delete
                                    </label>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No documents uploaded yet.</p>
                {% endif %}

                <!-- Form fields -->
                {{ form|crispy }}

                <!-- Form Buttons -->
                <div class="text-center mt-4">
                    <button type="submit" name="action" value="save_and_exit" class="btn btn-primary me-2">
                        <i class="bi bi-save me-1"></i> Save
                    </button>
                    <a href="{{ cancel_url }}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-circle me-1"></i> Cancel
                    </a>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script>
    // Initialize Bootstrap tooltips (if any)
    document.addEventListener('DOMContentLoaded', function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        tooltipTriggerList.forEach(function (tooltipTriggerEl) {
            new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });
</script>
{% endblock %}

bauteileDB/components/templates/components/article_name_column.html
<a href="{% url 'components:article_stock' record.article.pk %}?back_url={{ request.get_full_path|urlencode }}" class="smooth-link">
    {{ record.article.name }}
</a>

bauteileDB/components/templates/components/article_stock_list.html
{% extends "generic_table_list.html" %}

{% block content %}
    <h2>Article Stock: {{ article.name }}</h2>
    <p><strong>Manufacturer:</strong> {{ article.manufacturer }}</p>
    <p><strong>Description:</strong> {{ article.description }}</p>
    <p><strong>Catalog Number:</strong> {{ article.catalog_number }}</p>
    <!-- Add other article fields as needed -->

    <hr>

    <!-- List of PDFs associated with the article -->
    <h3>Associated Documents</h3>
    {% if article.documents.all %}
        <ul>
            {% for document in article.documents.all %}
                <li>
                    <a href="{{ document.file.url }}" target="_blank">{{ document.file.name }}</a>
                    {% if document.description %}
                        - {{ document.description }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No associated documents found.</p>
    {% endif %}

    <hr>
    <!-- Edit Button -->
    <a href="{% url 'components:article_update' article.pk %}?back_url={{ request.get_full_path|urlencode }}" class="btn btn-sm btn-primary">
        <i class="bi bi-pencil-square"></i> Edit Article
    </a>

    <hr>


    <!-- Render the table for items of this article -->
    {{ block.super }}
{% endblock %}

bauteileDB/components/templates/components/generic_form.html
{% extends "base.html" %}

{% block content %}
<h2>{{ page_title }}</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{{ cancel_url }}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

bauteileDB/components/templates/components/item_actions_column.html
<!-- Edit Button with Tooltip -->
<a href="{% url 'components:item_update' record.pk %}?next={{ request.get_full_path|urlencode }}"
   class="btn btn-sm btn-primary"
   data-bs-toggle="tooltip"
   data-bs-placement="top"
   title="Edit this item">
    <i class="bi bi-pencil-square"></i> Edit
</a>

<!-- Split Button with Tooltip -->
{% if record.article.unit and record.article.unit.unit_of_measurement == 'pcs' %}
    {% if record.quantity == 1 %}
        <!-- Don't show the button if unit is 'pcs' and quantity is 1 -->
    {% else %}
        <a href="{% url 'components:item_split' record.pk %}?next={{ request.get_full_path|urlencode }}"
           class="btn btn-sm btn-warning"
           data-bs-toggle="tooltip"
           data-bs-placement="top"
           title="Split this item into multiple items">
            <i class="bi bi-scissors"></i> Split
        </a>
    {% endif %}
{% else %}
    <a href="{% url 'components:item_split' record.pk %}?next={{ request.get_full_path|urlencode }}"
       class="btn btn-sm btn-warning"
       data-bs-toggle="tooltip"
       data-bs-placement="top"
       title="Split this item into multiple items">
        <i class="bi bi-scissors"></i> Split
    </a>
{% endif %}

<!-- Info Button with Tooltip -->
<a href="{% url 'components:item_detail' record.pk %}?next={{ request.get_full_path|urlencode }}"
   class="btn btn-sm btn-info"
   data-bs-toggle="tooltip"
   data-bs-placement="top"
   title="View item details">
    <i class="bi bi-info-circle"></i> Info
</a>

bauteileDB/components/templates/components/item_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ page_title }}</h2>

<!-- Item Information Card -->
<div class="card mb-4">
  <div class="card-header">
    <strong>Item Information</strong>
  </div>
  <div class="card-body">
    <!-- We'll display fields in a table for clarity -->
    <table class="table table-bordered mb-0">
      <tbody>
        <tr>
          <th>Article</th>
          <td>
            {% if item.article %}
              {{ item.article.name }}
            {% else %}
              &mdash;
            {% endif %}
          </td>
        </tr>
        <tr>
          <th>Serial Number</th>
          <td>{{ item.serial_number|default:"(none)" }}</td>
        </tr>
        <tr>
          <th>Location</th>
          <td>
            {% if item.storage_location %}
              {{ item.storage_location.name }}
            {% else %}
              &mdash;
            {% endif %}
            {% if item.storage_sublocation %}
              / {{ item.storage_sublocation.name }}
            {% endif %}
            {% if item.storage_drawer %}
              / {{ item.storage_drawer.name }}
            {% endif %}
          </td>
        </tr>
        <tr>
          <th>Quantity</th>
          <td>{{ item.quantity_with_unit }}</td>
        </tr>
        <tr>
          <th>Assigned Project</th>
          <td>
            {% if item.assigned_project %}
              {{ item.assigned_project.name }}
            {% else %}
              &mdash;
            {% endif %}
          </td>
        </tr>
        <tr>
          <th>Assigned Subproject</th>
          <td>
            {% if item.assigned_subproject %}
              {{ item.assigned_subproject.name }}
            {% else %}
              &mdash;
            {% endif %}
          </td>
        </tr>
        <tr>
          <th>Assigned Assembly</th>
          <td>
            {% if item.assigned_assembly %}
              {{ item.assigned_assembly.name }}
            {% else %}
              &mdash;
            {% endif %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<!-- Show "Order" button only if no serial number -->
{% if not item.serial_number %}
  <a href="{% url 'components:item_order' item.pk %}?next={{ request.get_full_path|urlencode }}"
     class="btn btn-info btn-lg mb-3">
     <i class="bi bi-cart-plus"></i> Order
  </a>
{% endif %}


<hr>

<!-- List of PDFs / Documents associated with the item -->
<h3>Associated Documents</h3>
{% if item.documents.all %}
    <ul class="list-group mb-4">
        {% for document in item.documents.all %}
            <li class="list-group-item">
                <a href="{{ document.file.url }}" target="_blank">{{ document.file.name }}</a>
                {% if document.description %}
                    - {{ document.description }}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No associated documents found.</p>
{% endif %}

<hr>

<!-- Edit Button -->
<a href="{% url 'components:item_update' item.pk %}?next={{ request.get_full_path|urlencode }}"
   class="btn btn-sm btn-primary">
    <i class="bi bi-pencil-square"></i> Edit
</a>
<!-- Download QR Code Button -->
<a class="btn btn-warning btn-lg mb-3"
   href="{% url 'components:item_qr_download' item.pk %}">
   <i class="bi bi-qr-code"></i> Download QR
</a>
<!-- Back Button -->
{% if back_url %}
    <a href="{{ back_url }}" class="btn btn-secondary">
        <i class="bi bi-arrow-left me-2"></i> Back
    </a>
{% else %}
    <a href="javascript:history.back()" class="btn btn-secondary">
        <i class="bi bi-arrow-left me-2"></i> Back
    </a>
{% endif %}

{% endblock %}

bauteileDB/components/templates/components/item_order.html
<!-- templates/components/item_order.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container my-4">

    <!-- Title with item and location info -->
    <h2>
        Orders for Item: {{ item.article.name }}
        {% if item.serial_number %}
          (SN: {{ item.serial_number }})
        {% endif %}
    </h2>

    {% if item.storage_location or item.storage_sublocation or item.storage_drawer %}
    <p>
        <strong>Location:</strong>
        {% if item.storage_location %}
          {{ item.storage_location.name }}
        {% endif %}
        {% if item.storage_sublocation %}
          / {{ item.storage_sublocation.name }}
        {% endif %}
        {% if item.storage_drawer %}
          / {{ item.storage_drawer.name }}
        {% endif %}
    </p>
    {% endif %}

    <p>Current Quantity in Stock: {{ item.quantity_with_unit }}</p>
    <hr/>

    <!-- Existing Orders Table -->
    <h4>Existing Orders</h4>
    <table class="table table-striped align-middle">
        <thead>
            <tr>
                <th>Date</th>
                <th>Quantity Ordered</th>
                <th>Modified By</th>
                <th class="text-end">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.date|date:"Y-m-d H:i" }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.modified_by }}</td>
                <td class="text-end">
                    <!-- Finish Order Button -->
                    <form action="{% url 'components:order_finish' item_pk=item.pk order_pk=order.pk %}" 
                          method="POST" 
                          class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">
                            <i class="bi bi-check-circle"></i> Finish
                        </button>
                    </form>
                    
                    <!-- Delete Order Button -->
                    <form action="{% url 'components:order_delete' item_pk=item.pk order_pk=order.pk %}"
                          method="POST"
                          class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i> Delete
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}

        {% if orders|length == 0 %}
            <tr>
                <td colspan="4" class="text-center">No orders yet.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <hr/>

    <!-- New Order Form -->
    <h4>Place a New Order</h4>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="mb-3">
            <label for="id_quantity" class="form-label">Quantity</label>
            {{ form.quantity }}
            {% if form.quantity.errors %}
                <div class="text-danger">{{ form.quantity.errors }}</div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Create Order and send Mail</button>
        <a href="{{ cancel_url }}" class="btn btn-secondary">Cancel</a>
    </form>

</div>
{% endblock %}