bauteileDB/bauteileDB/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView
from usermanagement import views as register_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('core/', include('core.urls')),
    path('components/', include('components.urls')),
    path('projects/', include('projects.urls')),
    path('rooms/', include('rooms.urls')),
    path('vendors/', include('vendors.urls')),
    path('import/', include('importexport.urls')),
    path('log/', include('log.urls')),
    path('tools/', include('tools.urls')),
    
    path('', include('django.contrib.auth.urls')),  # Auth URLs
    path('logout/', include('usermanagement.urls'), name='logout'),

    path('', RedirectView.as_view(url='/components/articles/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bauteileDB/core/urls.py
from django.urls import path

from django.conf.urls.static import static
from bauteileDB import settings


from .views.api_views import bulk_delete, generic_autocomplete, get_assembly_location, QRCodeView
from .views.generic_views import HelpPageView

app_name = 'core'

urlpatterns = [
    path('<str:model_name>/<str:app_name>/bulk-delete/', bulk_delete, name='bulk_delete'),
    path('autocomplete/<str:model_name>/<str:field_name>/', generic_autocomplete, name='generic-autocomplete'),
    path('api/assembly-location/', get_assembly_location, name='assembly-location'),
    path('qr-code/', QRCodeView.as_view(), name='qr_code'),
    path('help/', HelpPageView.as_view(), name='help'),
]

bauteileDB/log/urls.py
from django.urls import path
from .views import LogListView

app_name = 'log'

urlpatterns = [
    path('', LogListView.as_view(), name='log_list'),
]

bauteileDB/rooms/urls.py
from django.urls import path
from .views import *

app_name = 'rooms'

urlpatterns = [
    #---------------Location URLs---------------
    path('', LocationListView.as_view(), name='location_list'),
    path('add/', LocationAddView.as_view(), name='location_add'),
    path('<int:pk>/update/', LocationUpdateView.as_view(), name='location_update'),
    
    #---------------Sublocation URLs---------------
    path('<int:location_id>/sublocations/', SublocationListView.as_view(), name='sublocation_list'),
    path('<int:location_id>/sublocations/add/', SublocationAddView.as_view(), name='sublocation_add'),
    path('sublocations/<int:pk>/update/', SublocationUpdateView.as_view(), name='sublocation_update'),
    
    #---------------Drawer URLs---------------
    path('<int:sublocation_id>/drawers/', DrawerListView.as_view(), name='drawer_list'),
    path('<int:sublocation_id>/drawers/add/', DrawerAddView.as_view(), name='drawer_add'),
    path('drawers/<int:pk>/update/', DrawerUpdateView.as_view(), name='drawer_update'),
]

bauteileDB/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
    #---------------Location URLs---------------
    path('', ToolListView.as_view(), name='tool_list'),
    path('add-tool/', ToolAddView.as_view(), name='tool_add'),
    path('<int:pk>/update/', ToolUpdateView.as_view(), name='tool_update'),
    path('<int:pk>/borrow/', BorrowToolView.as_view(), name='borrow_tool'),
    path('<int:pk>/return/', ReturnToolView.as_view(), name='return_tool'),
]

bauteileDB/vendors/urls.py
from django.urls import path
from .views import *

app_name = 'vendors'

urlpatterns = [
    #---------------Manufacturer URLs---------------
    path('manufacturers', ManufacturerListView.as_view(), name='manufacturer_list'),
    path('add-manufacturer/', ManufacturerAddView.as_view(), name='manufacturer_add'),
    path('<int:pk>/update-manufacturer/', ManufacturerUpdateView.as_view(), name='manufacturer_update'),
    path('item/export/', ManufacturerExportView.as_view(), name='manufacturer_export'),

    #---------------Supplier URLs---------------
    path('suppliers', SupplierListView.as_view(), name='supplier_list'),
    path('add-supplier/', SupplierAddView.as_view(), name='supplier_add'),
    path('<int:pk>/update-supplier/', SupplierUpdateView.as_view(), name='supplier_update'),
    path('item/export/', SupplierExportView.as_view(), name='supplier_export'),
]

bauteileDB/core/views/generic_views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView
from django.shortcuts import get_object_or_404, redirect
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.views.generic import ListView
from urllib.parse import urlencode, urlparse, parse_qs, urlunparse
from log.utils import log_to_database
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.views import View
from django.http import HttpResponse
import csv


class HelpPageView(TemplateView):
    template_name = "help_template.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Help"
        return context


class GenericTableView(SingleTableMixin, FilterView, ListView):
    """
    A reusable table view with filtering, sorting, pagination, and dynamic bulk actions.
    """
    table_class = None  # This will be set in specific views
    filterset_class = None  # This will be set in specific views
    template_name = 'generic_table_list.html'  # Default template
    ordering = None  # To handle ordering of the table

    def get_table_class(self):
        if not self.table_class:
            model_name = self.model.__name__
            table_class_name = f'{model_name}Table'
            self.table_class = globals().get(table_class_name)
        return self.table_class
 
    def get_table(self, **kwargs):
        table = super().get_table(**kwargs)

        # Get the fields from the table class's Meta
        table_fields = getattr(table.Meta, 'fields', None)
        if table_fields:
            table_fields = list(table_fields)

            # Exclude 'actions' and 'selection' unless included via GET parameters
            include_actions = self.request.GET.get('include_actions', 'false').lower() == 'true'
            include_selection = self.request.GET.get('include_selection', 'false').lower() == 'true'

            if 'actions' in table_fields and not include_actions:
                table_fields.remove('actions')
            if 'selection' in table_fields and not include_selection:
                table_fields.remove('selection')

            # Apply additional exclusions from 'exclude_column' GET parameter
            exclude_columns = self.request.GET.getlist('exclude_column')
            for col in exclude_columns:
                if col in table_fields:
                    table_fields.remove(col)

            # Update the table's fields
            table.fields = table_fields

        return table

    def get_filterset_class(self):
        if not self.filterset_class:
            model_name = self.model.__name__
            filter_class_name = f'{model_name}Filter'
            self.filterset_class = globals().get(filter_class_name)
        return self.filterset_class

    def get_paginate_by(self, queryset):
        page_size = self.request.GET.get('page_size', 25)
        return page_size

    def get_ordering(self):
        sort = self.request.GET.get('sort')
        if sort:
            return sort.split('.')
        return super().get_ordering()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        model_meta = self.model._meta

        # Adding verbose names
        context['verbose_name'] = getattr(model_meta, 'verbose_name', self.model.__name__)
        context['verbose_name_plural'] = getattr(model_meta, 'verbose_name_plural', f'{self.model.__name__}s')

        # Add custom title if present in the URL
        custom_title = self.request.GET.get('custom_title')
        if custom_title:
            context['custom_title'] = custom_title
        else:
            context['custom_title'] = context['verbose_name_plural']
            
        # Handle back_url
        back_url = self.request.GET.get('back_url')
        if back_url:
            url_parts = urlparse(back_url)
            query_params = parse_qs(url_parts.query)
            query_params.pop('selection', None)
            query_params.pop('page', None)  # Remove 'page' parameter
            filtered_query = urlencode(query_params, doseq=True)
            filtered_back_url = urlunparse((
                url_parts.scheme,
                url_parts.netloc,
                url_parts.path,
                url_parts.params,
                filtered_query,
                url_parts.fragment
            ))
            context['back_url'] = filtered_back_url

        # Handle bulk actions
        bulk_actions_modal= kwargs.get('bulk_actions_modal', [])
        for action in bulk_actions_modal:
            action.setdefault('modal_template', None)
            action.setdefault('modal_js', None)

        context['bulk_actions_modal'] = bulk_actions_modal
        
        bulk_actions= kwargs.get('bulk_actions', [])
        context['bulk_actions'] = bulk_actions
        return context
    
    def dispatch(self, request, *args, **kwargs):
    # Check for the 'page' parameter and any other query params
        page_param = request.GET.get('page')
        other_params = {key: val for key, val in request.GET.items() if key != 'page'}

        # If there's only a 'page' parameter and no other query parameters, skip logging
        if not page_param or other_params:
            user = request.user if request.user.is_authenticated else None
            view_name = self.__class__.__name__
            log_message = f"{view_name} accessed by {user} from IP {request.META.get('REMOTE_ADDR')}"
            log_to_database('DEBUG', log_message, user=user)

        # Proceed with the normal dispatch method
        return super().dispatch(request, *args, **kwargs)


class GenericExportView(View):
    model = None  # Set this in the subclass
    filterset_class = None  # Set this in the subclass
    table_class = None  # Set this in the subclass

    def get(self, request, *args, **kwargs):
        # Get the queryset with the applied filters
        queryset = self.get_filtered_queryset()

        # Generate the CSV response
        response = HttpResponse(content_type='text/csv')
        filename = self.get_filename()
        response['Content-Disposition'] = f'attachment; filename="{filename}"'

        # Write the CSV data
        writer = csv.writer(response)

        # Get the field names
        field_names = self.get_field_names()

        # Write the header row
        writer.writerow(field_names)

        for obj in queryset:
            row = [self.get_field_value(obj, field) for field in field_names]
            writer.writerow(row)

        return response

    def get_filtered_queryset(self):
        queryset = self.model.objects.all()
        # Apply filtering using the filterset_class
        if self.filterset_class:
            filterset = self.filterset_class(self.request.GET, queryset=queryset)
            queryset = filterset.qs

        # Additional filtering for specific article
        article_id = self.kwargs.get('article_id')
        if article_id:
            queryset = queryset.filter(article_id=article_id)

        return queryset

    def get_field_names(self):
        if self.table_class:
            # Use the fields from the table's Meta class
            table_fields = getattr(self.table_class.Meta, 'fields', None)
            if table_fields:
                # Exclude 'selection' and 'actions' if present
                fields = [field for field in table_fields if field not in ('selection', 'actions')]
                return fields
        # Default to all fields
        return [field.name for field in self.model._meta.fields]

    def get_field_value(self, obj, field_name):
        # Handle related fields and method fields
        try:
            value = getattr(obj, field_name)
            if callable(value):
                value = value()
            return str(value)
        except AttributeError:
            return ''

    def get_filename(self):
        return f"{self.model._meta.verbose_name_plural}.csv"
    
    def dispatch(self, request, *args, **kwargs):
    # Log access to this view using your custom logging function
        user = request.user if request.user.is_authenticated else None
        view_name = self.__class__.__name__  # Get the name of the view class
        log_message = f"{view_name} accessed by {user} from IP {request.META.get('REMOTE_ADDR')}"
        
        # Call log_to_database function to save the log entry
        log_to_database('INFO', log_message, user=user)

        # Proceed with the normal dispatch method
        return super().dispatch(request, *args, **kwargs)


class GenericAddView(LoginRequiredMixin,CreateView):
    template_name = 'generic_form.html'  # Default form template
    page_title = "Add New"  # Default title for adding a model
    login_url = '/login'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if 'parent_model' in self.kwargs:
            parent_model = self.kwargs.get('parent_model')
            parent_id = self.kwargs.get('parent_id')
            parent = get_object_or_404(parent_model, pk=parent_id)
            kwargs['initial'] = {self.kwargs.get('parent_field'): parent}
            kwargs[self.kwargs.get('parent_field')] = parent
        return kwargs

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        return next_url or reverse_lazy(self.success_url_name or '/')

    def get_cancel_url(self):
        next_url = self.request.GET.get('next')
        return next_url or reverse_lazy(self.cancel_url_name or self.success_url_name or '/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['next'] = self.request.GET.get('next', '/')
        context['cancel_url'] = self.get_cancel_url()
        

bauteileDB/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <!-- Responsive Meta Tag -->
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- SEO Meta Tags -->
   <meta name="description" content="Tool for tracking where items are.">
   <meta name="author" content="Max-Planck-Institut für extraterrestrische Physik">
   <title>{% block title %}AntoniusDB{% endblock %}</title>
   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
   <!-- Bootstrap Icons -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
   <!-- jQuery UI CSS -->
   <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
   <!-- Custom CSS -->
   <link rel="stylesheet" href="{% static 'styles/table.css' %}">
   {% block extra_head %}{% endblock %}
</head>
    <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'components:article_list' %}">AntoniusDB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'article_list' %}active{% endif %}" href="{% url 'components:article_list' %}">Articles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'all_items_list' %}active{% endif %}" href="{% url 'components:all_items_list' %}">Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'tool_list' %}active{% endif %}" href="{% url 'tools:tool_list' %}">Tools</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'manufacturer_list' %}active{% endif %}" href="{% url 'vendors:manufacturer_list' %}">Manufacturers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'supplier_list' %}active{% endif %}" href="{% url 'vendors:supplier_list' %}">Suppliers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'location_list' %}active{% endif %}" href="{% url 'rooms:location_list' %}">Locations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'project_list' %}active{% endif %}" href="{% url 'projects:project_list' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'Help' %}active{% endif %}" href="{% url 'core:help' %}">Help</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'import_export_csv' %}active{% endif %}" href="{% url 'importexport:import_export_csv' %}">Import-CSV</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'log-list' %}active{% endif %}" href="{% url 'log:log_list' %}">Logs</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Logged in as: <strong>{{ user.username }}</strong>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                                <!-- Add other user-related links here if needed -->
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


   <!-- Main Content Area -->
   <div class="container mt-4">
       {% block content %}{% endblock %}
   </div>

   <!-- Footer -->
   <footer class="bg-light text-center text-lg-start mt-auto">
       <div class="container p-4">
           
       </div>
   </footer>

   <!-- Scripts -->
   <!-- jQuery and jQuery UI -->
   <script src="https://code.jquery.com/jquery-3.6.0.min.js" defer></script>
   <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" defer></script>
   <!-- Bootstrap JS (includes Popper.js) -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
   <!-- Custom JS -->
   <script src="{% static 'js/autocomplete.js' %}" defer></script>
   <script src="{% static 'js/advanced_filter.js' %}" defer></script>
   <script src="{% static 'js/main.js' %}" defer></script>
   {% block extra_js %}{% endblock %}
</body>
</html>

bauteileDB/templates/generic_table_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load static %}
{% load querystring_tags %}

{% block content %}
<!-- Main Container with Data Attributes -->
<div id="main-container" data-verbose-name="{{ verbose_name|escapejs }}" data-verbose-name-plural="{{ verbose_name_plural|escapejs }}">

    <!-- Page Title -->
    <h2>{{ custom_title|default:verbose_name_plural }}</h2>

    <!-- Display Django Messages -->
    {% if messages %}
      <div class="alert alert-info">
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      </div>
    {% endif %}

    <!-- Back Button -->
    {% if back_url %}
    <a href="{{ back_url }}" class="btn btn-secondary">
        <i class="bi bi-arrow-left me-2"></i> Back
    </a>
{% else %}
    <a href="javascript:history.back()" class="btn btn-secondary">
        <i class="bi bi-arrow-left me-2"></i> Back
    </a>
{% endif %}

    <!-- Search and Advanced Filter Section -->
    <div class="row mb-3">
        <div class="col-md-8">
            <!-- Search Form -->
            <form method="GET" class="d-flex" id="searchForm">
                <!-- Preserve Existing GET Parameters Except 'search' and 'page' -->
                {% for key, value in request.GET.items %}
                    {% if key != 'search' and key != 'page' %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                <div class="input-group">
                    {{ filter.form.search }}
                    <button class="btn btn-primary" type="submit">
                        <i class="bi bi-search"></i> Search
                    </button>
                    {% if request.GET.search %}
                        <a href="{{ request.path }}?{% for key, value in request.GET.items %}{% if key != 'search' and key != 'page' %}{{ key }}={{ value|urlencode }}&{% endif %}{% endfor %}" class="btn btn-outline-secondary">Clear</a>
                    {% endif %}
                </div>
            </form>
        </div>
        <div class="col-md-4 text-md-end mt-2 mt-md-0">
            <!-- Advanced Filter Button -->
            <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#filterFormContainer" aria-expanded="false" aria-controls="filterFormContainer" id="advancedFilterButton">
                <i class="bi bi-funnel"></i> Advanced Filter
            </button>
        </div>
    </div>

    <!-- Advanced Filter Section -->
    <div id="filterFormContainer" class="collapse">
      <div class="filter-container border border-3 rounded-5 p-4 mb-3 bg-light">
        <h5>Advanced Filter</h5>
        <form method="GET" class="mb-3" id="advancedFilterForm">
          <div class="row">
              {% for field in filter.form.visible_fields %}
                  {% if field.name != 'search' %}
                      <div class="col-md-4 mb-3">
                          {{ field|as_crispy_field }}
                      </div>
                  {% endif %}
              {% endfor %}
          </div>
          <!-- Preserve Existing GET Parameters Except 'page' -->
          {% for key, value in request.GET.items %}
              {% if key != 'page' %}
                  <input type="hidden" name="{{ key }}" value="{{ value }}">
              {% endif %}
          {% endfor %}
          <div class="mt-2 d-flex justify-content-end">
            <button id="applyFilterButton" type="submit" class="btn btn-primary me-2">Apply Filters <i class="bi bi-filter"></i></button>
            <a href="{{ request.path }}" class="btn btn-secondary">Clear Filters</a>
          </div>
        </form>
      </div>
    </div>

    <!-- Add Button -->
    {% if add_button_url and add_button_label %}
    <div class="mb-3">
      <a href="{{ add_button_url }}?next={{ request.get_full_path|urlencode }}" class="btn btn-primary">
        {{ add_button_label }}
      </a>
    </div>
    {% endif %}
    <!-- Export and QR Code Buttons -->
    {% if export_button_url%}
    <div class="mb-3 d-flex justify-content-end">
      <!-- QR Code Download Button -->
      <a href="{% url 'core:qr_code' %}?url={{ request.build_absolute_uri|urlencode }}"
        download="qr_code-{{ custom_title|default:request.path|slugify }}.png"
        class="btn btn-secondary">
          <i class="bi bi-qr-code"></i> QR Code
      </a>
      <a href="{{ export_button_url }}?{{ request.GET.urlencode }}" class="btn btn-secondary">
          <i class="bi bi-file-earmark-spreadsheet"></i> Export
      </a>
    </div>
    {% endif %}


    <!-- Bulk Actions and Selection Indicators -->
    <div class="row mb-3">
      <!-- First Column: Bulk Action Buttons -->
      <div class="col-md-6 d-flex flex-wrap align-items-center">
          {% for action in bulk_actions_modal %}
              <button type="button" class="btn {{ action.class }} bulk-action-button-modal me-2 mb-2"
                      data-bs-toggle="modal" data-bs-target="{{ action.modal_target }}"
                      data-url="{{ action.bulk_delete_url }}" data-method="{{ action.method|default:'POST' }}">
                  {{ action.name }}
              </button>
          {% endfor %}

          {% for action in bulk_actions %}
              <button type="button" class="btn {{ action.class }} bulk-action-button me-2 mb-2"
                      data-url="{{ action.bulk_action_url }}" data-method="{{ action.method }}">
                  {{ action.name }}
              </button>
          {% endfor %}
      </div>

      <!-- Second Column: Selection Indicators and Page Size Selector -->
      <div class="col-md-6 d-flex align-items-center justify-content-md-end flex-wrap">
          <!-- Selected Count Badge -->
          <span id="selected-count" class="badge bg-primary me-3 mb-2" style="display: none;">
              0 {{ verbose_name_plural }} selected
          </span>

          <!-- Clear Selection Button -->
          <button type="button" class="btn btn-outline-secondary btn-sm me-3 mb-2" id="clear-selection-button" style="display: none;">
              <i class="bi bi-x-circle me-1"></i> Clear Selection
          </button>

          <!-- Notice for Selections on Other Pages -->
          <span id="other-pages-notice" class="badge bg-warning text-dark me-3 mb-2" style="display: none;">
              Selections exist on other pages.
          </span>

          <!-- Items Per Page Dropdown -->
          <label for="page-size" class="me-2 mb-2">Items per page:</label>
          <form method="GET" id="page-size-form" class="d-inline mb-2">
              <!-- Preserve Existing GET Parameters Except 'page_size' and 'page' -->
              {% for key, value in request.GET.items %}
                  {% if key != 'page_size' and key != 'page' %}
                      <input type="hidden" name="{{ key }}" value="{{ value }}">
                  {% endif %}
              {% endfor %}
              <input type="hidden" name="page" value="1">
              <select id="page-size" name="page_size" class="form-select form-select-sm d-inline-block w-auto" onchange="this.form.submit()">
                  <option value="25" {% if request.GET.page_size == '25' %}selected{% endif %}>25</option>
                  <option value="50" {% if request.GET.page_size == '50' %}selected{% endif %}>50</option>
                  <option value="100" {% if request.GET.page_size == '100' %}selected{% endif %}>100</option>
                  <option value="100000" {% if request.GET.page_size == '1000000' %}selected{% endif %}>All</option>
              </select>
          </form>
      </div>
    </div>


    <!-- Bulk Action Modals -->
    {% for action in bulk_actions_modal %}
    {% include action.modal_template %}
    {% endfor %}

    <!-- Items Table Wrapped in Responsive Container -->
    <div class="table-responsive">
        <form method="POST" id="bulkActionForm">
          {% csrf_token %}
          {% render_table table %}
          <input type="hidden" name="next" value="{{ request.get_full_path }}">
        </form>
    </div>

    <!-- Pagination Controls -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% querystring page=1 %}" data-paginator-link aria-label="First">
              <span aria-hidden="true">&laquo;&laquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?{% querystring page=page_obj.previous_page_number %}" data-paginator-link aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">&laquo;&laquo;</span>
          </li>
          <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
          </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
          {% if i >= page_obj.number|add:'-4' and i <= page_obj.number|add:'4' %}
            {% if page_obj.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?{% querystring page=i %}" data-paginator-link>{{ i }}</a>
              </li>
            {% endif %}
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% querystring page=page_obj.next_page_number %}" data-paginator-link aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?{% querystring page=page_obj.paginator.num_pages %}" data-paginator-link aria-label="Last">
              <span aria-hidden="true">&raquo;&raquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
          </li>
          <li class="page-item disabled">
            <span class="page-link">&raquo;&raquo;</span>
          </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

</div> <!-- Close the main-container div -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/bulk_actions.js' %}" defer></script>
<script src="{% static 'js/toggle_message.js' %}" defer></script>
<script>
    // Initialize Bootstrap tooltips
    document.addEventListener('DOMContentLoaded', function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        tooltipTriggerList.forEach(function (tooltipTriggerEl) {
            new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });
</script>
{% endblock %}